services:
  php:
    image: fsilva/php:8.3-apache
    ports:
      - 80
    volumes:
      - ./:/var/www/app
    environment:
      - WEBROOT=public
      - USE_XDEBUG=yes
    depends_on:
      - database

  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: forum
