services:
  php:
    build: docker/php
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/app
    environment:
      - WEBROOT=public
      - USE_XDEBUG=yes
      - ENABLE_XDEBUG_FOR_MAC=yes
      - ENABLE_OPCACHE=no
    depends_on:
      - database

  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: forum
